### ISSUE TITLE
新版20240916数据库有问题

### ISSUE THREAD

**Issue by jianghu73441** [vkdfkc/V2M2#1]
1.没有添加货币表1－6
2.学习技能后，重新登录db报错，游戏内技能消失

**Comment by vkdfkc** [comment]
1、使用数据库升级工具
2、同上

**Comment by jianghu73441** [comment]
还有就是sdb数据编辑工具只提供了导出数据没有批量导入功能，以前其他引擎做的数据库无法导入sdb数据，不知道有什么办法？
另外登录器配置器不能用了吗，只能用ip版？正常配置完后，登录器进入游戏不读取补丁，并且输入账号后无法登录，可在读取画面！

**Comment by vkdfkc** [comment]
去官网下载20240916版，SDB你把后缀改为CSV然后用Excel或者WPS去处理就行了，改完记得把后缀改回去，其它引擎的你数据导出成CSV然后自己用Excel处理就行了，没有Excel用记事本也行。BDE的数据库用版本转换器或者数据库转换工具转成SDB也行。

**Comment by jianghu73441** [comment]
好的，有交流群吗？

**Comment by jianghu73441** [comment]
1.建议m2技能里骷髅神兽技能增加强化设置，例如强化1－3重召唤一种自设怪物，强化4－6重召唤另一种……
2.登录器配置器配置登录器依然不读素材(黑屏)，依照以前教学视频生成登录器后，m2生成列表文件全部放到资源文件夹/Data文件夹内后，进入游戏还是黑屏！使用登录器配置器内的构建功能一键生成登录器 全部覆盖到客户端也是一样！不知道哪里的问题！
3.是否能增加脚本释放技能功能，例如佩戴指定物品后，可以实现普通攻击几率释放雷电术，或者释放雷电术触发诱惑之光等等……即铭文系统……
4.启动引擎时游戏网关偶尔出现连接不上问题，设置向导内点击恢复默认该选项后，重启引擎便会正常
5.lua功能方面刚接触，不是太懂！本引擎是否只能通过插件扩展模式增加功能，不知能否参照vvm2引擎方式，直接使用QF.lua方式制作lua脚本……
6.刺客潜行技能在攻击怪物后走一段距离使用，依然会被怪物攻击！
第一次接触归来版本引擎，很多功能不太了解，请谅解……

**Comment by vkdfkc** [comment]
群里聊吧：592533745
